// ============================================================
//  BAZAAR — ENGLISH TRANSLATIONS for shop/tools/plans content
// ============================================================
// This file ONLY contains English text for product names, descriptions,
// badges, features etc. It does NOT define any logic, IDs, prices, icons,
// or structure — those all stay in js/config.js and must never be touched
// or duplicated here.
//
// Every key below already matches a real id from js/config.js — do NOT
// add, remove, or rename any key. Only replace the French string VALUES
// with their English translation. If a key is left as-is (French text),
// the site automatically falls back to French for that one entry — so an
// incomplete file never breaks the site, it just leaves that bit untranslated.

const CONFIG_EN = {
  // Top-level shop category names (id -> English name)
  categories: {
    discord: "Discord",
    streaming: "Streaming",
    games: "Games",
    vpn: "VPN",
    transfert: "Transfer",
  },

  // Shop sub-groups: id -> { name, badges[], longDesc, warning }
  // badges array must keep the SAME NUMBER of entries, in the same order.
  groups: {
    nitro: {
      name: "Nitro",
      badges: ["✅ Account required", "⚡ Delivered in minutes", "🔒 Secure gift link"],
      longDesc: "Get Discord Nitro at the best price. Our gift links require no password or account sharing — just redeem the code and enjoy.",
      warning: "Non-refundable after delivery of the gift link.",
    },
    boost: {
      name: "Server Boost",
      badges: ["✅ No password required", "⚡ Most orders within minutes", "🔒 100% Secure checkout"],
      longDesc: "Boost your Discord server to unlock features like animated icons, better audio quality, custom invite links, and server banners. Bazaar provides affordable Discord boosts with fast delivery and simple ordering.",
      warning: "Non-refundable. Boosts are active for the chosen duration.",
    },
    aged: {
      name: "Aged Accounts",
      badges: ["📅 Certified year", "🔐 Passwords and emails delivered", "🔒 Verification included"],
      longDesc: "Authentic Discord accounts created in the stated year, perfect for projects requiring an account with history. Creation year verified before delivery.",
      warning: "Non-refundable. Do not violate Discord's ToS.",
    },
    members: {
      name: "Server Members (Online/Offline)",
      badges: ["📈 Gradual delivery", "✅ Secure method", "🔒 No account access needed"],
      longDesc: "Increase visibility for your server or social profile. Gradual delivery for a natural result. Compatible with Discord, Instagram, TikTok, YouTube and more.",
      warning: "Non-refundable. Results vary depending on the platform.",
    },
    decorations: {
      name: "Decorations",
      badges: ["✅ Via gift link", "⚡ Delivered in minutes", "🔒 No account sharing"],
      longDesc: "Exclusive Discord profile decorations delivered via gift link. No account sharing required — just redeem the link.",
      warning: "Non-refundable after delivery of the gift link.",
    },
    streaming_netflix: {
      name: "Netflix",
      badges: ["✅ Full access", "🔒 Premium account", "⚠️ Do not change the password"],
      longDesc: "Premium Netflix accounts — access to the entire movie and series catalog in HD/4K without a monthly subscription.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_crunchy: {
      name: "Crunchyroll",
      badges: ["✅ Full access", "🔒 Premium account", "⚠️ Do not change the password"],
      longDesc: "Crunchyroll Premium — all anime streaming ad-free and in simulcast.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_youtube: {
      name: "YouTube Premium",
      badges: ["✅ Full access", "🔒 Premium account", "⚡ Fast delivery"],
      longDesc: "YouTube Premium — ad-free, music included (YouTube Music), offline downloads and background playback.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_deezer: {
      name: "Deezer Premium",
      badges: ["✅ Full access", "🔒 Lifetime account", "⚠️ Do not change the password"],
      longDesc: "Deezer Premium lifetime — HD quality music, ad-free, unlimited downloads.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_prime: {
      name: "Prime Video",
      badges: ["✅ Full access", "🔒 Premium account", "⚠️ Do not change the password"],
      longDesc: "Amazon Prime Video — full catalog of movies, series and Amazon Originals.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_nba: {
      name: "NBA League Pass",
      badges: ["✅ Full access", "🔒 Premium account", "⚡ Fast delivery"],
      longDesc: "NBA League Pass Premium — watch all NBA games live and on replay throughout the season.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_ufc: {
      name: "UFC Fight Pass",
      badges: ["✅ Full access", "🔒 Lifetime account", "⚡ Fast delivery"],
      longDesc: "UFC Fight Pass lifetime — all UFC events live and the complete fight archive.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_hbo: {
      name: "HBO Max",
      badges: ["✅ Full access", "🔒 Premium account", "⚡ Fast delivery"],
      longDesc: "HBO Max Premium — full HBO catalog, Warner Bros, DC Comics and exclusive productions.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_dazn: {
      name: "DAZN",
      badges: ["✅ Full access", "🌍 Random country", "⚡ Fast delivery"],
      longDesc: "DAZN — the sports streaming platform: football, boxing, F1, tennis and much more. Country may vary.",
      warning: "Do not change the password. Country may vary depending on stock. Non-refundable.",
    },
    streaming_paramount: {
      name: "Paramount+ EU",
      badges: ["✅ Full access", "🔒 Lifetime account", "⚡ Fast delivery"],
      longDesc: "Paramount+ EU lifetime — Paramount, CBS, Nickelodeon movies and series plus live sports.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    streaming_capcut: {
      name: "CapCut Pro",
      badges: ["✅ Full access", "🔒 Premium account", "⚡ Fast delivery"],
      longDesc: "CapCut Pro — all premium effects, exclusive templates and watermark-free video export.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    roblox: {
      name: "Robux",
      badges: ["✅ Via Pls Donate", "⚡ Fast delivery", "🔒 Compatible with any Roblox account"],
      longDesc: "Thousands of Robux instantly on your account via the Pls Donate method. Provide your Roblox username when ordering.",
      warning: "Non-refundable. Double-check your username before ordering.",
    },
    epicgames: {
      name: "Epic Games",
      badges: ["✅ Full Access", "⚡ Fast delivery", "🎮 Email + Password included"],
      longDesc: "Epic Games accounts with hundreds of premium games. Full Access — email and password provided, full account access.",
      warning: "Do not change account information. Non-refundable.",
    },
    steam_action: {
      name: "Action & Adventure",
      badges: ["✅ Steam FA account", "🎮 Game included", "⚡ Fast delivery"],
      longDesc: "Steam Full Access accounts with the corresponding game already installed. Email and password provided. Accounts may contain other bonus games.",
      warning: "Do not change account information. Non-refundable.",
    },
    steam_horror: {
      name: "Survival & Horror",
      badges: ["✅ Steam FA account", "🎮 Game included", "⚡ Fast delivery"],
      longDesc: "Steam Full Access accounts with the corresponding game already installed. Email and password provided. Accounts may contain other bonus games.",
      warning: "Do not change account information. Non-refundable.",
    },
    steam_simulation: {
      name: "Simulation & Sandbox",
      badges: ["✅ Steam FA account", "🎮 Game included", "⚡ Fast delivery"],
      longDesc: "Steam Full Access accounts with the corresponding game already installed. Email and password provided. Accounts may contain other bonus games.",
      warning: "Do not change account information. Non-refundable.",
    },
    steam_multi: {
      name: "Multiplayer & Misc",
      badges: ["✅ Steam FA account", "🎮 Game included", "⚡ Fast delivery"],
      longDesc: "Steam Full Access accounts with the corresponding game already installed. Email and password provided. Accounts may contain other bonus games.",
      warning: "Do not change account information. Non-refundable.",
    },
    valorant: {
      name: "Valorant Account",
      badges: ["✅ Full Access", "🎮 VP inventory included", "⚡ Fast delivery"],
      longDesc: "Valorant EU accounts with VP (Valorant Points) inventory already present. Full Access — email and password provided, full account access.",
      warning: "Do not change account information. Non-refundable.",
    },
    nordvpn: {
      name: "NordVPN",
      badges: ["✅ Full access", "🌍 5000+ servers", "🔒 No-logs policy"],
      longDesc: "NordVPN Premium — 100% secure browsing with 5000+ servers in 60 countries. Protection against trackers, malware and DNS leaks.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    ipvanish: {
      name: "IPVanish",
      badges: ["✅ Full access", "🌍 Multi-country", "🔒 Certified no-logs"],
      longDesc: "IPVanish Premium — ultra-fast VPN with certified no-logs policy and unlimited speeds on all devices.",
      warning: "Do not change the password or account information. Non-refundable.",
    },
    ltc: {
      name: "LTC",
      badges: ["⚡ Market rate", "🔒 Trusted service", "💬 Via Discord ticket"],
      longDesc: "Easily exchange your crypto (LTC) for PayPal. Service available via Discord ticket, rate negotiated in real time.",
      warning: "Rates vary according to the market. Check the rate before proceeding.",
    },
  },

  // Individual shop/tool items: id -> { name, desc }
  items: {
    nitro_boost_gl: { name: "Nitro Boost — Gift Link", desc: "Instant delivery via Discord." },
    nitro_basic_gl: { name: "Nitro Basic — Gift Link", desc: "Nitro Classic via gift link." },
    nitro_boost_3m: { name: "Nitro Boost 3 Months (FA)", desc: "Full access Nitro Boost 3 months account." },
    nitro_promo_1m: { name: "Nitro Promo 1 Month", desc: "Nitro promo 1 month." },
    nitro_promo_3m: { name: "Nitro Promo 3 Months", desc: "Nitro promo 3 months." },
    boost_14_1m: { name: "x14 Boosts — 1 Month", desc: "14 server boosts for 1 month." },
    boost_14_3m: { name: "x14 Boosts — 3 Months", desc: "14 server boosts for 3 months." },
    aged_2015: { name: "2015 Account", desc: "Discord account created in 2015." },
    aged_2016: { name: "2016 Account", desc: "Discord account created in 2016." },
    aged_2017: { name: "2017 Account", desc: "Discord account created in 2017." },
    aged_2018: { name: "2018 Account", desc: "Discord account created in 2018." },
    aged_2019: { name: "2019 Account", desc: "Discord account created in 2019." },
    aged_2020: { name: "2020 Account", desc: "Discord account created in 2020." },
    aged_2021: { name: "2021 Account", desc: "Discord account created in 2021." },
    aged_2022: { name: "2022 Account", desc: "Discord account created in 2022." },
    aged_2023: { name: "2023 Account", desc: "Discord account created in 2023." },
    aged_2024: { name: "2024 Account", desc: "Discord account created in 2024." },
    aged_2025: { name: "2025 Account", desc: "Discord account created in 2025." },
    aged_2026: { name: "2026 Account", desc: "Discord account created in 2026." },
    members_offline: { name: "1k Members Offline", desc: "Offline members for your server." },
    members_online: { name: "1k Members Online", desc: "Active members for your server." },
    followers_nw: { name: "Followers/Views Without Guarantee", desc: "1k follows, views or likes without guarantee." },
    followers_fw: { name: "Followers/Views Guaranteed", desc: "1k follows, views or likes guaranteed." },
    decors_random: { name: "Random Decoration", desc: "Via gift link, fast delivery." },
    netflix_life: { name: "Netflix Premium", desc: "Netflix premium account." },
    crunchyroll_life: { name: "Crunchyroll Premium", desc: "Crunchyroll premium account." },
    youtube_1m: { name: "YouTube Premium — 1 Month", desc: "1 month ad-free access." },
    deezer_life: { name: "Deezer Premium Lifetime", desc: "Lifetime Deezer account." },
    prime_1m: { name: "Prime Video — 1 Month", desc: "Prime Video 1 month access." },
    nba_prem: { name: "NBA League Pass Premium", desc: "NBA League Pass access." },
    ufc_life: { name: "UFC Fight Pass Lifetime", desc: "Lifetime UFC account." },
    hbo_prem: { name: "HBO Max Premium", desc: "HBO Max premium account." },
    dazn_rand: { name: "DAZN — Random Country", desc: "DAZN account." },
    paramount_life: { name: "Paramount+ EU Lifetime", desc: "Lifetime Paramount+ account." },
    capcut_prem: { name: "CapCut Pro Premium", desc: "CapCut Pro account." },
    robux_1k: { name: "Robux 1.000 – 2.500", desc: "Delivery via Pls Donate." },
    robux_2500: { name: "Robux 2.500 – 5.000", desc: "Delivery via Pls Donate." },
    robux_5k: { name: "Robux 5.000 – 10.000", desc: "Delivery via Pls Donate." },
    robux_10k: { name: "Robux 10.000 – 15.000", desc: "Delivery via Pls Donate." },
    robux_50k: { name: "Robux 50.000+", desc: "Delivery via Pls Donate." },
    epic_50: { name: "Epic Games [50-100 Games] FA", desc: "Account with 50 to 100 games." },
    epic_100: { name: "Epic Games [100-200 Games] FA", desc: "Account with 100 to 200 games." },
    epic_200: { name: "Epic Games [200-350 Games] FA", desc: "Account with 200 to 350 games." },
    epic_350: { name: "Epic Games [350+ Games] FA", desc: "Account with 350+ games." },
    steam_gow: { name: "God of War", desc: "Steam account — God of War." },
    steam_cp2077: { name: "Cyberpunk 2077", desc: "Steam account — Cyberpunk 2077." },
    steam_hogwarts: { name: "Hogwarts Legacy", desc: "Steam account — Hogwarts Legacy." },
    steam_witcher3: { name: "The Witcher 3", desc: "Steam account — The Witcher 3." },
    steam_gta5: { name: "GTA 5", desc: "Steam account — GTA 5." },
    steam_uncharted: { name: "UNCHARTED: Legacy of Thieves", desc: "Steam account — Uncharted." },
    steam_jc4: { name: "Just Cause 4", desc: "Steam account — Just Cause 4." },
    steam_re8: { name: "Resident Evil Village", desc: "Steam account — RE Village." },
    steam_hitman: { name: "Hitman", desc: "Steam account — Hitman." },
    steam_outlast: { name: "Outlast", desc: "Steam account — Outlast." },
    steam_outlast2: { name: "Outlast 2", desc: "Steam account — Outlast 2." },
    steam_forest: { name: "The Forest", desc: "Steam account — The Forest." },
    steam_sons: { name: "Sons of the Forest", desc: "Steam account — Sons of the Forest." },
    steam_ark: { name: "ARK", desc: "Steam account — ARK." },
    steam_dbd: { name: "Dead by Daylight", desc: "Steam account — Dead by Daylight." },
    steam_phasmo: { name: "Phasmophobia", desc: "Steam account — Phasmophobia." },
    steam_backrooms: { name: "Escape the Backrooms", desc: "Steam account — Escape the Backrooms." },
    steam_raft: { name: "Raft", desc: "Steam account — Raft." },
    steam_fs25: { name: "Farming Simulator 25", desc: "Steam account — FS25." },
    steam_cs1: { name: "Cities: Skylines", desc: "Steam account — Cities Skylines." },
    steam_cs2: { name: "Cities: Skylines 2", desc: "Steam account — Cities Skylines 2." },
    steam_hf2: { name: "House Flipper 2", desc: "Steam account — House Flipper 2." },
    steam_gmod: { name: "Garry's Mod", desc: "Steam account — Garry's Mod." },
    steam_smarket: { name: "Supermarket Simulator", desc: "Steam account — Supermarket Simulator." },
    steam_ets2: { name: "Euro Truck Simulator 2", desc: "Steam account — ETS2." },
    steam_contraband: { name: "Contraband Police", desc: "Steam account — Contraband Police." },
    steam_assetto: { name: "Assetto Corsa", desc: "Steam account — Assetto Corsa." },
    steam_beamng: { name: "BeamNG.drive", desc: "Steam account — BeamNG.drive." },
    steam_sot: { name: "Sea of Thieves", desc: "Steam account — Sea of Thieves." },
    steam_amongus: { name: "Among Us", desc: "Steam account — Among Us." },
    steam_ron: { name: "Ready or Not", desc: "Steam account — Ready or Not." },
    steam_marvel: { name: "Marvel Rivals", desc: "Steam account — Marvel Rivals." },
    steam_detroit: { name: "Detroit: Become Human", desc: "Steam account — Detroit." },
    steam_wpe: { name: "Wallpaper Engine", desc: "Steam account — Wallpaper Engine." },
    steam_schedule1: { name: "Schedule 1", desc: "Steam account — Schedule 1." },
    val_1k_3k: { name: "Valorant EU [1.000–3.000 VP]", desc: "Account with 1000-3000 VP inventory." },
    val_3k_5k: { name: "Valorant EU [3.000–5.000 VP]", desc: "Account with 3000-5000 VP inventory." },
    val_5k_7k: { name: "Valorant EU [5.000–7.000 VP]", desc: "Account with 5000-7000 VP inventory." },
    val_7k_12k: { name: "Valorant EU [7.000–12.000 VP]", desc: "Account with 7000-12000 VP inventory." },
    val_15k_25k: { name: "Valorant EU [15.000–25.000 VP]", desc: "Account with 15000-25000 VP inventory." },
    nordvpn_prem: { name: "NordVPN Premium", desc: "NordVPN premium account." },
    ipvanish_prem: { name: "IPVanish Premium", desc: "IPVanish premium account." },
    exchange: { name: "LTC ↔ PayPal", desc: "Exchange at market rate." },
  },

  // Subscription plans: id -> { subtitle, features[] }
  // features array must keep the SAME NUMBER of entries, in the same order
  // as js/config.js (each index = the matching bullet point).
  plans: {
    plan_free: {
      subtitle: "Free basic access.",
      features: ["12 searches / 48h", "Paid tools", "Basic OSINT search", "Discord support"],
    },
    plan_starter: {
      subtitle: "More basic access.",
      features: ["24 searches / 48h", "Premium tool access", "Starter Discord role", "Priority in giveaways"],
    },
    plan_pro: {
      subtitle: "Serious pro access.",
      features: ["48 searches / 48h", "-10% on entire shop (Nitro...)", "Premium tool access", "Pro Discord role", "Full premium access", "Priority support", "Priority in giveaways"],
    },
    plan_lifetime: {
      subtitle: "Premium access for great services.",
      features: ["64 searches / 48h", "Tools & Shop for life", "-20% on entire shop (Nitro...)", "Custom voice channel on the Discord server", "Lifetime Discord role", "Full premium access", "Founder support", "Priority in giveaways"],
    },
  },

  // Free/premium tools: id -> { name, desc }
  tools: {
    t1: { name: "Sherlock", desc: "Hunt down social media accounts by username across social networks. Example: sherlock user123" },
    t2: { name: "Tor Tools", desc: "Best for safe, curated research; it filters illegal content and is endorsed by the Tor Project." },
    t3: { name: "[New] Discord Nuker", desc: "Boubou-Discord-Nuker — automated Discord server nuke." },
    t4: { name: "[Site] Verity Suite", desc: "Zlamana-VeritySuite — complete IT website & identity verification." },
    t5: { name: "DMALL Services discord", desc: "Boubou-DMALL — all-in-one suite of Discord tools and services." },
    t6: { name: "Nitro Generator", desc: "Discord-Nitro-Generator — generates Discord Nitro codes." },
    t8: { name: "Purple Grabber - Boubou", desc: "A Grabber with a lot of features ..." },
    t9: { name: "Database pack", desc: "Database pack (+10) - Buy on discord" },
    t10: { name: "Discord private vocal", desc: "Private vocal in the discord server" },
    t11: { name: "Database Searcher", desc: "Long file search tool." },
    t12: { name: "CrosshairX - cracked by boubou", desc: "In-game crosshair overlay." },
  },
};
